# Generated by Django 4.1.2 on 2023-01-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerDetails',
            new_name='Customerlogindb',
        ),
    ]
