# Generated by Django 4.1.2 on 2023-01-02 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP2', '0002_rename_customerdetails_customerlogindb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customerlogindb',
            new_name='CustomerDetails',
        ),
    ]
