# Generated by Django 4.1.2 on 2023-01-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP2', '0004_customeradminlogin_delete_customerdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customeradminlogin',
            new_name='CustomerDetails',
        ),
    ]
