# Generated by Django 4.1.2 on 2023-01-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP2', '0006_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.CharField(blank=True, max_length=50, null=True)),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('EmailID', models.EmailField(blank=True, max_length=50, null=True)),
                ('Website', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
