# Generated by Django 4.1.2 on 2023-01-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP2', '0010_delete_blogdb_delete_contactdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Totalprice', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
