# Generated by Django 4.1.2 on 2023-01-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP2', '0011_cartdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdb',
            name='Image',
            field=models.ImageField(null=True, upload_to='profile'),
        ),
    ]
