# Generated by Django 4.1.2 on 2022-12-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0002_westernwomendb'),
    ]

    operations = [
        migrations.CreateModel(
            name='westernmendb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DressName', models.CharField(blank=True, max_length=50, null=True)),
                ('Code', models.IntegerField(blank=True, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Image', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
