# Generated by Django 4.1.2 on 2022-12-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0004_accessoriesdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminpagedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('MobileNumber', models.IntegerField(blank=True, null=True)),
                ('EmailID', models.EmailField(blank=True, max_length=254, null=True)),
                ('Image', models.ImageField(upload_to='profile')),
                ('UserName', models.CharField(blank=True, max_length=50, null=True)),
                ('Password', models.CharField(blank=True, max_length=50, null=True)),
                ('ConfirmPassword', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
