# Generated by Django 4.1.2 on 2022-12-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0005_adminpagedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=50, null=True)),
                ('ProductName', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Description', models.CharField(blank=True, max_length=500, null=True)),
                ('Image', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
