# Generated by Django 4.1.2 on 2023-01-02 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0006_productdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productdb',
            new_name='productpagedb',
        ),
    ]
