# Generated by Django 4.1.2 on 2023-01-02 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0007_rename_productdb_productpagedb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productpagedb',
            new_name='productdb',
        ),
    ]
