# Generated by Django 4.1.2 on 2023-01-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0009_rename_productdb_productpagedb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpagedb',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
