# Generated by Django 4.1.2 on 2023-01-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0010_alter_productpagedb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpagedb',
            name='Image',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
