# Generated by Django 4.1.2 on 2023-01-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0011_alter_productpagedb_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='productpagedb',
            new_name='productdatabase',
        ),
    ]
