# Generated by Django 4.1.2 on 2023-01-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0012_rename_productpagedb_productdatabase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdatabase',
            old_name='Image',
            new_name='FileInput',
        ),
    ]
