# Generated by Django 4.1.2 on 2023-01-04 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP1', '0015_blogdb_contactdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogdb',
        ),
        migrations.DeleteModel(
            name='Contactdb',
        ),
    ]
